### ISSUE TITLE
all coverart removed

### ISSUE THREAD

**Issue by thomasf72** [keithgg/puddletag#289]
I want added a new TAG to many files from different albums with different coverart's 
I have select many files, and add the new TAG ... puddle tag have now remove all coverpictures 
Is this a bug, or a normal function?

**Comment by keithgg** [comment]
I'm not sure what you did. Can you go into more detail?

**Comment by thomasf72** [comment]
Hello

I load my Musicdirectory (complete) , select all files , go to expanded tag
(in german gui call "erweiterte Tags" ) and add one new TAG to all files.
puddletags (1.1.1) add the new TAG but removed all cover(pictures).

Greetings
Thomas




2016-05-05 20:46 GMT+02:00 Keith Grootboom <notifications@github.com>:

**Comment by keithgg** [comment]
Late reply, but this isn't quite a bug. There are many ways to work around this and you stumbled on the one case that doesn't work for you.

If you select multiple files, you'll the the cover art change to <keep> (or whatever the tranlation is). When you add an image, it's assumed that you want to "fix" (ie. overwrite) the cover art, because not all files have the same cover art and you're setting the definitive version.

If all the files had exactly the same cover art, it would work as you expect.

**Comment by thefoster** [comment]
I'd treat this as a bug.
Like in basic edit mode, when nothing is written if it hasn't changed.
I can confirm that this behaviour is still present in 2.4.0.
In extended edit mode i just changed one character in the comment field, which results in covers from all selected files are being removed (shouldn't happen IMHO)
No damage occoured (test case) and one can ship around that: simply no multi-select-edits in extended edit mode on different albums.
