### ISSUE TITLE
Can't write Bengali language in puddletag!

### ISSUE THREAD

**Issue by aagontuk** [keithgg/puddletag#295]
I am using Puddletag for more than a year. My previous OS was Ubunutu. Puddletag was okey in Ubuntu. I could write bengali language flawlessly in puddletag. I was using ibus for writing Bengali in ubuntu.

Now I have switched to Arch Linux and installed my favorite Puddletag. But I can't write Bengali in Puddletag. In Arch I am also using ibus for writing Bengali and its working fine in other applications.

What is the problem? How can I solve this?

Thanks!

**Comment by keithgg** [comment]
Do you get any sort of output on the console?

**Comment by rashfaqur** [comment]
Terminal output is just showing the version number and current locale.

```
puddletag Version: 1.1.1
Locale: en_US
```

Noticed another thing; if I copy Bengali text from somewhere and paste on puddletag it works.

**Comment by rashfaqur** [comment]
I think this is not puddletag related bug. Because I am having same issue in [konsole](https://konsole.kde.org/).

I am using [i3](https://i3wm.org/)( no DE ) window manager on Arch Linux. I am not sure yet why I am having this problem actually but may be its i3 related bug as I can write Benagli in other DEs in those softwares.

Already I have posted an [issue](https://www.reddit.com/r/i3wm/comments/4vydw9/cant_write_benglai_language_in_i3_in_some/?ref=share&ref_source=link) on i3 forum on reddit.

Thanks!

**Comment by keithgg** [comment]
Cool. Closing this.
