### ISSUE TITLE
Not available from brew anymore — How to install on macOS?

### ISSUE THREAD

**Issue by welpo** [keithgg/puddletag#318]
Some weeks/months ago the puddletag formula was removed from brew.

How do I properly install it on macOS now?
Or how do I install through brew, since `brew install puddletag` fails?

**Comment by chincheta0815** [comment]
homebrew deleted the formula due to the fact that qt4 is not supported anymore on macOS. 

Since puddletag has dependencies to pyqt4 it won't run.

I started trying to update puddletag to qt5 and python3 but it might take a while until I'm finished. Especially the qt stuff is tricky without help *hint*.
Am 22.11.16, 17:50, welpo <notifications@github.com> schrieb:

  
    
      Some weeks/months ago the puddletag formula was removed from brew.
    
    
      How do I properly install it on macOS now?
      Or how do I install through brew, since brew install puddletag fails?

**Comment by keithgg** [comment]
Brew removed support for qt4 which breaks puddletag. Closing this for now as I can't assist with compiling on OSX. Further discussion to happen in #300 .

**Comment by TomBugnon** [comment]
@keithgg puddletag 2.0.1 has been released, which is a port to python3 and pyqt5, so this can be reopened?

**Comment by sandrotosi** [comment]
@chincheta0815 hey! it looks like you were maintaining the brew installation of puddletag: would you be interested in resuming that effort, now that puddletag supports python3 and pyqt5?
