### ISSUE TITLE
Scanner limits length when writing filename to title tag. 

### ISSUE THREAD

**Issue by Budgie2** [keithgg/puddletag#340]
Running on openSUSE Leap 42.2 with KDE Desktop I am using scanner to write filenames to the title tags.  With a longish filenames I am finding that the text is curtailed and the last few words not written.  Is there a reason for limiting the length of the title tag text and can I change a setting to correct this?  I have tried and RTFM but am no wiser.

**Comment by bernd-wechner** [comment]
I'm not sure what you mean by "scanner" but you really need to specify the file format and the tag you're writing to to be sure. For example ID3v1 has some nasty length limits on tags. Nothing to do with the writer, just the format. It's not used much anymore and most will be using ID3v2 which is far less bothersome in this space. But each container format and tagging spec is different so what you're writing to makes all the difference. 

Puddletag uses the Mutagen library for writing tags and that's fairly well documented here:

http://mutagen.readthedocs.io/en/latest/api/base.html

**Comment by Budgie2** [comment]
Hi and many thanks for the reply.  I was referring to the Pattern Combo tool, (another tagging tool calls it a scanner,) my mistake.  Sorry I didn't give all details but I am using flac files with ID3v1 replaced by ID3v2.4 as set in Preferences>Tag.  
Meanwhile I have found an error in my OS which was waiting for a restart and that seems to have solved my problem.  I am still having trouble with the syntax and understanding how puddletag parses the filename. What is recognised as delimiter?  Is it space-space?

**Comment by keithgg** [comment]
Why are you using ID3 tags on your flac files? VorbisComments are the supported type for flac files.

There is no delimeter, just tags are stripped out. (Just read the docs on this, they need an update badly).

I'll explain by example. Let say you had the file named *1. Beck - Blue in C Minor (Reprise)*

* **%artist%** will match the whole thing giving you artist=1. Beck - Blue in C Minor (Reprise)
* **%artist% - %title%** gives artist=1. Beck; title=Blue in C Minor (Reprise)
* **%track% %artist% - %title%** becomes artist=Beck; title=Blue in C Minor (Reprise); track=1. [notice the dot since we didn't exclude it.
* **%track%. %artist% - %title%** becomes artist=Beck; title=Blue in C Minor (Reprise); track=1 [we added the . to the pattern, because we wanted to exclude it]
* **%track%. %artist% - %title% (%description%)** because we don't like track descriptions in the title gives us artist=Beck; title=Blue in C Minor (Reprise); track=1; description=Reprise

Closing this issue as invalid.

**Comment by bernd-wechner** [comment]
Just curious if the last example contains a typo. I would not expect to 
see (Reprise) in the title there - you list title=Blue in C Minor (Reprise)

**Comment by keithgg** [comment]
Not anymore ;-)
