### ISSUE TITLE
Stupid feature request: recognize "*.opus.ogg" as opus, not vorbis

### ISSUE THREAD

**Issue by Epicanis** [keithgg/puddletag#357]
Blame Google/Android: Android since "Lollipop" has had native opus support, but stupidly doesn't recognize ".opus" files, and Google doesn't seem to be interested in fixing this. Since ".opus" is "opus in ogg", naming opus files "*.ogg" makes Android magically recognize them.

Using ".opus.ogg" seems to be a convention for naming opus files for use in Android (and is technically correct anyway).  However, puddletag seems to assume that *.ogg is vorbis-in-ogg, regardless, so .opus files that have been named so as to be recognizeable to Android cannot be edited in puddletag.

(Alternatively, switch to interrogating the files directly to determine what's in them, a la the "file" command, but I'm guessing that's a bigger change than adding ".opus.ogg" to the "recognized file extensions" list.)

I can just rename files back and forth to update their metadata and then send them back to Android devices afterwards, so this is certainly not a fatal problem, just an annoying extra step.

**Comment by keithgg** [comment]
Easy enough to do. Next time I get time, will add.

**Comment by lopsided98** [comment]
I just ran into this issue, and looked through the code in the hopes of fixing it. The solution does not seem to be as simple as adding a new file extension, because the code only uses text after the final period as the extension. There is no general way to determine where the extension starts, because the file name may contain periods.

A simpler solution seems to be to set the extension for Ogg Vorbis to `None`, which causes the code to use `mutagen`'s score mechanism to detect the file type. This correctly detects Ogg Vorbis and Opus files with the `.ogg` extension. Possibly, all file types could use this mechanism, but I'm not sure this works in all cases.

**Comment by lopsided98** [comment]
See #413

**Comment by RafaelLinux** [comment]
I have same issue. I had several files with extension OGG that contains OPUS coded audio, but Puddletag doesn't show them.

**Comment by lopsided98** [comment]
@RafaelLinux Have you tried #413? Does it fix the problem for you?

**Comment by RafaelLinux** [comment]
I read it, but I didn't understand what to do. Do I need to compile my own version of Puddletag? In that case, I prefer to use file taggers alternatives that does recognize that OGG files while a patch is applied.

**Comment by lopsided98** [comment]
Puddletag is written in Python, so you don't need to compile it.

Clone my fork with `git clone https://github.com/lopsided98/puddletag.git -b ogg-opus-detection` and then run `python2 puddletag/source/puddletag`

I would like to get #413 merged, so it would be good to know if it works for you, but puddletag development does not seem very active since there have been no commits in over a year.

**Comment by keithgg** [comment]
Closed in the commit. Tested and working pyqt5 branch.

**Comment by RafaelLinux** [comment]
It works, but this way I can't launch this puddletag patched version with right click from Dolphin. I noticed that puddletag ways shows 0 as bitrate for "opus" files.
