### ISSUE TITLE
Tag to filename "/" omission issue

### ISSUE THREAD

**Issue by vijaygopal1234** [keithgg/puddletag#359]
I'm not sure if this is a bug or intended behavior so I will post and check for your opinions. 

```$if($not($neql(%__ext%,flac)),HQ/%artist% - %title%,Compressed/%track% - %title%)```

The directory structure inside the if statements is not expressed in tag to filename. The output ignores the characters and does not create the directories.

**Comment by keithgg** [comment]
Yeah. It's intentional. Any slashes(/) used inside $function won't result in a directory split. Just because, it was easy enough behaviour at the time. And lessons the risk of splits where none were intended.

Suggested solution. Create an action that has the filename renaming as one step and the dir renaming as another.
